name: geheim
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: geheim
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: geheim
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 3s
      retries: 5

  # Spring Boot application
  web:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/geheim
      SPRING_DATASOURCE_USERNAME: geheim
      SPRING_DATASOURCE_PASSWORD: geheim
    ports:
      - "8080:8080"
volumes:
  db-data:
